#!/bin/sh
set -eu

: "${APP_USER:?APP_USER is required}"
: "${APP_USER_PASSWORD:?APP_USER_PASSWORD is required}"
: "${ORACLE_DATABASE:=FREEPDB1}"

sqlplus -s / as sysdba <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER=${ORACLE_DATABASE};

DECLARE
  user_count NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO user_count
  FROM dba_users
  WHERE username = UPPER('${APP_USER}');

  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ${APP_USER} IDENTIFIED BY "${APP_USER_PASSWORD}" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER ${APP_USER} IDENTIFIED BY "${APP_USER_PASSWORD}"';
  END IF;

  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE MATERIALIZED VIEW TO ${APP_USER}';
  EXECUTE IMMEDIATE 'ALTER USER ${APP_USER} QUOTA UNLIMITED ON USERS';
END;
/
EXIT
SQL
