import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPaymentMethodToSales1779829540833 implements MigrationInterface {
    name = 'AddPaymentMethodToSales1779829540833'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_CUS_CEDULA"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ROLE_NAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USR_USERNAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USR_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USR_EMP_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SAL_NUM"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SAL_BRA_STA_CRE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRO_CODE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRO_CAT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_STR_MOV_PRO_CRE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SAL_DET_SAL_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INV_NUM"`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP CONSTRAINT "CK_USR_STA"`);
        await queryRunner.query(`ALTER TABLE "SALES" DROP CONSTRAINT "CK_SAL_STA"`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" DROP CONSTRAINT "CK_STR_TYP"`);
        await queryRunner.query(`ALTER TABLE "INVOICES" DROP CONSTRAINT "CK_INV_STA"`);
        await queryRunner.query(`ALTER TABLE "ERROR_LOGS" DROP CONSTRAINT "CK_ERR_TYP"`);
        await queryRunner.query(`CREATE TABLE "PASSWORD_RESET_TOKENS" ("id" uuid NOT NULL, "USER_ID" uuid NOT NULL, "TOKEN_HASH" character varying(64) NOT NULL, "EXPIRES_AT" TIMESTAMP(6) NOT NULL, "USED_AT" TIMESTAMP(6), "CRE_AT" TIMESTAMP NOT NULL DEFAULT now(), "REQUEST_IP" character varying(45), "REQUEST_USER_AGENT" character varying(512), CONSTRAINT "PK_a3b657f47196c1e05a0fb8dcc65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP COLUMN "ROL_USR"`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD "CURRENT_PAS_HASH" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD "PAS_EXPIRED" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "SALES" ADD "PAY_MET_SAL" character varying(20) NOT NULL DEFAULT 'CASH'`);
        await queryRunner.query(`ALTER TABLE "USER_BRANCHES" ADD CONSTRAINT "PK_844c9bbc603b09f05911757a4ae" PRIMARY KEY ("USR_ID", "BRA_ID")`);
        await queryRunner.query(`ALTER TABLE "CUSTOMERS" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "CUSTOMERS" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "CUSTOMERS" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ROLES" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ROLES" ADD CONSTRAINT "UQ_7cb58899a22a78ca8ee8537b02d" UNIQUE ("NAM_ROL")`);
        await queryRunner.query(`ALTER TABLE "ROLES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" ADD CONSTRAINT "PK_f4406efa2f818440e96231e41ab" PRIMARY KEY ("USR_ID")`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "USERS" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD CONSTRAINT "UQ_1b967f6670e0c10ee447c4db4d5" UNIQUE ("EMP_ID")`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD CONSTRAINT "UQ_6fc499ee60e1e6483380535728d" UNIQUE ("USR_USR")`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD CONSTRAINT "UQ_77cc7a1532acfed8a7b8e3cb299" UNIQUE ("EMA_USR")`);
        await queryRunner.query(`ALTER TABLE "USERS" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "USERS" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TAX_RATES" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "TAX_RATES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TAX_RATES" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "SALES" ADD CONSTRAINT "UQ_910647b45afc1be42d11339f62d" UNIQUE ("SAL_NUM")`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "DIS_AMO_SAL" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "CATEGORIES" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "CATEGORIES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "CATEGORIES" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ADD CONSTRAINT "UQ_5b6dc0d0f43e56843c7049091c6" UNIQUE ("COD_PRO")`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "SALE_DETAILS" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "INVOICE_SERIES" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "INVOICE_SERIES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "INVOICE_SERIES" ALTER COLUMN "UPD_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "INVOICE_ITEMS" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ADD CONSTRAINT "UQ_7fb1a719f138cc5dc9056399402" UNIQUE ("INV_NUM")`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ALTER COLUMN "STA_INV" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ERROR_LOGS" ALTER COLUMN "CRE_AT" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UX_USER_ROLES_USR_ID" ON "USER_ROLES" ("USR_ID") `);
        await queryRunner.query(`CREATE INDEX "IDX_SAL_DET_SAL_ID" ON "SALE_DETAILS" ("CRE_AT") `);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" ADD CONSTRAINT "FK_f4406efa2f818440e96231e41ab" FOREIGN KEY ("USR_ID") REFERENCES "USERS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" ADD CONSTRAINT "FK_6ef8db4752ed6a6b299c849c713" FOREIGN KEY ("ROL_ID") REFERENCES "ROLES"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALES" ADD CONSTRAINT "FK_386624bc3ee8af97e4773b73487" FOREIGN KEY ("CUS_ID") REFERENCES "CUSTOMERS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALES" ADD CONSTRAINT "FK_37e9d16f4fd58d2e6ff3db7b422" FOREIGN KEY ("CAS_USR_ID") REFERENCES "USERS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALES" ADD CONSTRAINT "FK_1a4b0235dd2781ea6a27264fc7a" FOREIGN KEY ("TAX_RAT_ID") REFERENCES "TAX_RATES"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ADD CONSTRAINT "FK_5440f52cd3cd176dcc8279fd97e" FOREIGN KEY ("CAT_ID") REFERENCES "CATEGORIES"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" ADD CONSTRAINT "FK_a5f54e4d31c3486fa33bab128d1" FOREIGN KEY ("PRO_ID") REFERENCES "PRODUCTS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" ADD CONSTRAINT "FK_5bc6fa2cfc40ff9cc3670dfd8b6" FOREIGN KEY ("USR_ID") REFERENCES "USERS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "USER_BRANCHES" ADD CONSTRAINT "FK_649196aa73cb055e0f216c2e6ed" FOREIGN KEY ("USR_ID") REFERENCES "USERS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALE_DETAILS" ADD CONSTRAINT "FK_04983d65d60031dd79b99259429" FOREIGN KEY ("SAL_ID") REFERENCES "SALES"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALE_DETAILS" ADD CONSTRAINT "FK_740dc2ea47acf13f537f48c717d" FOREIGN KEY ("PRO_ID") REFERENCES "PRODUCTS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "INVOICE_ITEMS" ADD CONSTRAINT "FK_d63fd44056931a37eb3bfe2b3fe" FOREIGN KEY ("ID_INV_DET") REFERENCES "INVOICES"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "INVOICE_ITEMS" ADD CONSTRAINT "FK_24bbb98d5e7f08f49659bb6cd2a" FOREIGN KEY ("ID_PRO_DET") REFERENCES "PRODUCTS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ERROR_LOGS" ADD CONSTRAINT "FK_dac07d521dcbceb40cfb1cd355a" FOREIGN KEY ("USR_ID") REFERENCES "USERS"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ERROR_LOGS" DROP CONSTRAINT "FK_dac07d521dcbceb40cfb1cd355a"`);
        await queryRunner.query(`ALTER TABLE "INVOICE_ITEMS" DROP CONSTRAINT "FK_24bbb98d5e7f08f49659bb6cd2a"`);
        await queryRunner.query(`ALTER TABLE "INVOICE_ITEMS" DROP CONSTRAINT "FK_d63fd44056931a37eb3bfe2b3fe"`);
        await queryRunner.query(`ALTER TABLE "SALE_DETAILS" DROP CONSTRAINT "FK_740dc2ea47acf13f537f48c717d"`);
        await queryRunner.query(`ALTER TABLE "SALE_DETAILS" DROP CONSTRAINT "FK_04983d65d60031dd79b99259429"`);
        await queryRunner.query(`ALTER TABLE "USER_BRANCHES" DROP CONSTRAINT "FK_649196aa73cb055e0f216c2e6ed"`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" DROP CONSTRAINT "FK_5bc6fa2cfc40ff9cc3670dfd8b6"`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" DROP CONSTRAINT "FK_a5f54e4d31c3486fa33bab128d1"`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" DROP CONSTRAINT "FK_5440f52cd3cd176dcc8279fd97e"`);
        await queryRunner.query(`ALTER TABLE "SALES" DROP CONSTRAINT "FK_1a4b0235dd2781ea6a27264fc7a"`);
        await queryRunner.query(`ALTER TABLE "SALES" DROP CONSTRAINT "FK_37e9d16f4fd58d2e6ff3db7b422"`);
        await queryRunner.query(`ALTER TABLE "SALES" DROP CONSTRAINT "FK_386624bc3ee8af97e4773b73487"`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" DROP CONSTRAINT "FK_6ef8db4752ed6a6b299c849c713"`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" DROP CONSTRAINT "FK_f4406efa2f818440e96231e41ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SAL_DET_SAL_ID"`);
        await queryRunner.query(`DROP INDEX "public"."UX_USER_ROLES_USR_ID"`);
        await queryRunner.query(`ALTER TABLE "ERROR_LOGS" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ALTER COLUMN "STA_INV" SET DEFAULT 'ISSUED'`);
        await queryRunner.query(`ALTER TABLE "INVOICES" DROP CONSTRAINT "UQ_7fb1a719f138cc5dc9056399402"`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "INVOICE_ITEMS" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "INVOICE_SERIES" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "INVOICE_SERIES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "INVOICE_SERIES" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "SALE_DETAILS" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" DROP CONSTRAINT "UQ_5b6dc0d0f43e56843c7049091c6"`);
        await queryRunner.query(`ALTER TABLE "PRODUCTS" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "CATEGORIES" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "CATEGORIES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "CATEGORIES" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "DIS_AMO_SAL" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "SALES" DROP CONSTRAINT "UQ_910647b45afc1be42d11339f62d"`);
        await queryRunner.query(`ALTER TABLE "SALES" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "TAX_RATES" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TAX_RATES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TAX_RATES" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "USERS" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "USERS" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP CONSTRAINT "UQ_77cc7a1532acfed8a7b8e3cb299"`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP CONSTRAINT "UQ_6fc499ee60e1e6483380535728d"`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP CONSTRAINT "UQ_1b967f6670e0c10ee447c4db4d5"`);
        await queryRunner.query(`ALTER TABLE "USERS" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "USER_ROLES" DROP CONSTRAINT "PK_f4406efa2f818440e96231e41ab"`);
        await queryRunner.query(`ALTER TABLE "ROLES" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ROLES" DROP CONSTRAINT "UQ_7cb58899a22a78ca8ee8537b02d"`);
        await queryRunner.query(`ALTER TABLE "ROLES" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "CUSTOMERS" ALTER COLUMN "UPD_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "CUSTOMERS" ALTER COLUMN "CRE_AT" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "CUSTOMERS" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "USER_BRANCHES" DROP CONSTRAINT "PK_844c9bbc603b09f05911757a4ae"`);
        await queryRunner.query(`ALTER TABLE "SALES" DROP COLUMN "PAY_MET_SAL"`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP COLUMN "PAS_EXPIRED"`);
        await queryRunner.query(`ALTER TABLE "USERS" DROP COLUMN "CURRENT_PAS_HASH"`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD "ROL_USR" character varying(50)`);
        await queryRunner.query(`DROP TABLE "PASSWORD_RESET_TOKENS"`);
        await queryRunner.query(`ALTER TABLE "ERROR_LOGS" ADD CONSTRAINT "CK_ERR_TYP" CHECK ((("EXC_TYP")::text = ANY ((ARRAY['VALIDATION_ERROR'::character varying, 'DATABASE_ERROR'::character varying, 'AUTHENTICATION_ERROR'::character varying, 'AUTHORIZATION_ERROR'::character varying, 'BUSINESS_RULE_ERROR'::character varying, 'EXTERNAL_SERVICE_ERROR'::character varying, 'UNEXPECTED_ERROR'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "INVOICES" ADD CONSTRAINT "CK_INV_STA" CHECK ((("STA_INV")::text = ANY ((ARRAY['ISSUED'::character varying, 'CANCELLED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "STOCK_MOVEMENTS" ADD CONSTRAINT "CK_STR_TYP" CHECK ((("TYP_MOV")::text = ANY ((ARRAY['IN'::character varying, 'OUT'::character varying, 'SALE'::character varying, 'ADJUSTMENT'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "SALES" ADD CONSTRAINT "CK_SAL_STA" CHECK ((("STA_SAL")::text = ANY ((ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "USERS" ADD CONSTRAINT "CK_USR_STA" CHECK ((("STA_USR")::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying])::text[])))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_INV_NUM" ON "INVOICES" ("INV_NUM") `);
        await queryRunner.query(`CREATE INDEX "IDX_SAL_DET_SAL_ID" ON "SALE_DETAILS" ("SAL_ID") `);
        await queryRunner.query(`CREATE INDEX "IDX_STR_MOV_PRO_CRE" ON "STOCK_MOVEMENTS" ("PRO_ID", "CRE_AT") `);
        await queryRunner.query(`CREATE INDEX "IDX_PRO_CAT" ON "PRODUCTS" ("CAT_ID") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PRO_CODE" ON "PRODUCTS" ("COD_PRO") `);
        await queryRunner.query(`CREATE INDEX "IDX_SAL_BRA_STA_CRE" ON "SALES" ("BRA_ID", "STA_SAL", "CRE_AT") `);
        await queryRunner.query(`CREATE INDEX "IDX_SAL_NUM" ON "SALES" ("SAL_NUM") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USR_EMP_ID" ON "USERS" ("EMP_ID") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USR_EMAIL" ON "USERS" ("EMA_USR") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USR_USERNAME" ON "USERS" ("USR_USR") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ROLE_NAME" ON "ROLES" ("NAM_ROL") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_CUS_CEDULA" ON "CUSTOMERS" ("CED_CUS") `);
    }

}
